Public Class frmReimprimirFacturas
    Dim LNEG As New List(Of String)
    Dim LDE As New List(Of String)
    Dim LTIPO As New List(Of String)
    Private Sub frmReimprimirFacturas_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        Me.Icon = frmPrincipal.Icon
        VISUALIZACION(Me)

        'LLENACOMBOBOX(CBEMISOR, LDE, "SELECT NOMBRE,RFC FROM EMISORES WHERE EMPRESA=" + frmPrincipal.CORPORATIVO.ToString, frmPrincipal.CadenaConexion)
        LLENACOMBOBOX2LISTAS(CBEMISOR, LDE, LTIPO, "SELECT NOMBRE,TIPO,RFC FROM EMISORES WHERE EMPRESA=" + frmPrincipal.CORPORATIVO.ToString + "", frmPrincipal.CadenaConexion)
    End Sub

    Private Sub CBEMISOR_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CBEMISOR.SelectedIndexChanged
        LLENACOMBOBOX2(CBNEG, LNEG, "SELECT CLAVE,NOMBRE FROM NEGOCIOS WHERE RFC='" + CBEMISOR.Text + "' ORDER BY NOMBRE", frmPrincipal.CadenaConexion, "Todos los Negocios", "")
        LBLDE.Text = LDE(CBEMISOR.SelectedIndex)
    End Sub

    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button1.Click
        CARGADATOS()
    End Sub
    Private Sub CARGADATOS()
        If Not frmPrincipal.CHECACONX Then
            Exit Sub
        End If
        Dim QUERY As String
        QUERY = "SELECT F.RFCEMISOR,F.SERIE,F.FOLIO,N.NOMBRE NEGOCIO,F.RFCCLIENTE,C.NOMBRE CLIENTE,CONVERT(VARCHAR(10),F.FECHA,103)FECHA,F.SUBTOTAL,F.IVA,F.TOTAL,F.RETISR RETENCIONISR,F.RETIVA RETENCIONIVA,IMPRIMIR=CONVERT(BIT,0,0),E.NOMBRE ESTADO,F.VCFD [Versión] FROM FACTURAS F INNER JOIN NEGOCIOS N ON F.RFCEMISOR=N.RFC AND F.NEGOCIO=N.CLAVE INNER JOIN CLIENTES C ON F.RFCCLIENTE=C.RFC INNER JOIN METODOSPAGOS M ON F.METODOPAGO=M.CLAVE INNER JOIN ESTADOSFACTURA E ON F.ESTADO=E.CLAVE WHERE F.RFCEMISOR='" + CBEMISOR.Text + "' AND F.FECHA>=@INI AND F.FECHA<@FIN "
        If CBNEG.SelectedIndex <> 0 Then
            QUERY += " AND F.NEGOCIO='" + LNEG(CBNEG.SelectedIndex) + "'"
        End If
        QUERY += " ORDER BY F.FECHA"
        DGV.DataSource = LLENATABLAIF(QUERY, frmPrincipal.CadenaConexion, DTDE.Value.Date, DTHASTA.Value.Date.AddDays(1))
        DGV.Columns(0).ReadOnly = True
        DGV.Columns(1).ReadOnly = True
        DGV.Columns(2).ReadOnly = True
        DGV.Columns(3).ReadOnly = True
        DGV.Columns(4).ReadOnly = True
        DGV.Columns(5).ReadOnly = True
        DGV.Columns(6).ReadOnly = True
        DGV.Columns(7).ReadOnly = True
        DGV.Columns(8).ReadOnly = True
        DGV.Columns(9).ReadOnly = True
        DGV.Columns(10).ReadOnly = True
        DGV.Columns(11).ReadOnly = True
        DGV.Columns(13).ReadOnly = True
        DGV.Columns(14).ReadOnly = True
        CHECATABLA()

    End Sub
    Private Sub CHECATABLA()
        'Dim S, I, T, RISR, RIVA As Double
        'S = 0
        'I = 0
        'T = 0
        'RISR = 0
        'RIVA = 0
        'Dim X As Integer
        'For X = 0 To DGV.Rows.Count - 1
        '    If DGV.Item(13, X).Value = 2 Then
        '        S += DGV.Item(8, X).Value
        '        I += DGV.Item(9, X).Value
        '        T += DGV.Item(10, X).Value
        '        RISR += DGV.Item(11, X).Value
        '        RIVA += DGV.Item(12, X).Value
        '    End If
        'Next
        'LBLS.Text = FormatNumber(S, 2).ToString
        'LBLI.Text = FormatNumber(I, 2).ToString
        'LBLT.Text = FormatNumber(T, 2).ToString
        'LBLRISR.Text = FormatNumber(RISR, 2).ToString
        'LBLRIVA.Text = FormatNumber(RIVA, 2).ToString
    End Sub
    Dim NI As String
    Private Sub BTNIMPRIMIR_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles BTNIMPRIMIR.Click
        Dim xyz As Short
        xyz = MessageBox.Show("¿Desea imprimir las Facturas Marcadas?", "Aviso", MessageBoxButtons.YesNo, MessageBoxIcon.Question, MessageBoxDefaultButton.Button1)
        If xyz <> 6 Then
            Exit Sub
        End If
        NI = ""
        frmSeleccionarImpresora.ShowDialog()
        If frmSeleccionarImpresora.DialogResult = Windows.Forms.DialogResult.Yes Then
            NI = frmSeleccionarImpresora.NIMPRESORA
            MOSTRAR()        
        End If

    End Sub
    Private Sub MOSTRAR()
        Dim X As Integer
        Dim ESTADO As String
        For X = 0 To DGV.Rows.Count - 1
            If CType(DGV.Item(12, X).Value, Boolean) Then
                Dim QUERY As String
                ESTADO = DGV.Item(13, X).Value.ToString
                If DGV.Item(14, X).Value = "3.3" Then
                    QUERY = "SELECT * FROM VRFACTURA33 F where F.RFCEMISOR='" + CBEMISOR.Text + "' AND F.SERIE='" + DGV.Item(1, DGV.CurrentRow.Index).Value.ToString + "' AND F.FOLIO=" + DGV.Item(2, DGV.CurrentRow.Index).Value.ToString
                    Dim REP As New rptFacturaGenericaV33
                    IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)

                Else
                    If LTIPO(CBEMISOR.SelectedIndex) = 2 Then
                        'QUERY = "SELECT F.RFCEMISOR,E.NOMBRE NOMBREFISCAL,F.FECHA,F.SERIE,F.SUBTOTAL,F.IVA,F.DESCUENTO,F.TOTAL,F.CCLETRA CANTIDADCONLETRA,F.CERTIFICADOUSA NOCERTIFICADO,F.FOLIO,DBO.DOMICILIOMATRIZ(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOMATRIZ,DBO.DOMICILIOEXPEDICION(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOEXPEDICION,E.LOGOTIPO,E.LOGORFC,E.LOGOBIDIMENSIONAL CBBEMISOR,F.RFCCLIENTE,F.NOMBRE NOMBRECLIENTE,DBO.DIRECCIONCLI1(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI1,DBO.DIRECCIONCLI2(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI2,M.NOMBRE METODOPAGO,FP.NOMBRE FORMAPAGO,F.CADENAORIGINAL,F.SELLO SELLODIGITAL,F.SELLOSAT,F.UUID,P.CODIGO,P.CANTIDAD,          P.DESCRIPCION,CONVERT(NUMERIC(15,2),P.VALORUNITARIO,2)VALORUNITARIO,CONVERT(NUMERIC(15,2),P.IMPORTE,2)IMPORTE,F.RETISR,F.RETIVA,F.NOAPROBACION,F.AÑOAPROBACION,F.CBB CBBFACTURA,P.UNIDAD,F.DIGITOSTC,E.REGIMEN,TXTPAGARE=DBO.TXTPAGARE(F.RFCEMISOR,F.SERIE,F.FOLIO),F.COMENTARIO,    P.IEPS,             P.IVA DIVA,IMPORTELIC=(P.IMPORTE+P.IVA+P.IEPS),E.CURP,F.COCSAT,P.DESCUENTO DESCUENTOD,CP.NOMBRE CONDICIONESDEPAGO,T.DESCRIPCION TIPOCOMPROBANTE FROM FACTURAS F INNER JOIN EMISORES E ON F.RFCEMISOR=E.RFC INNER JOIN FORMASPAGO FP ON F.FORMAPAGO=FP.CLAVE INNER JOIN METODOSPAGOS M ON F.METODOPAGO=M.CLAVE INNER JOIN CONFIGURACION CON ON E.RFC=CON.RFC INNER JOIN NEGOCIOS N ON F.RFCEMISOR=N.RFC AND F.NEGOCIO=N.CLAVE INNER JOIN CLIENTES C ON F.RFCCLIENTE=C.RFC INNER JOIN DOMICILIOSCLIENTES D ON F.RFCCLIENTE=D.RFC AND F.DOMICILIOCLIENTE=D.REGISTRO INNER JOIN DETALLEFACTURAS P ON F.RFCEMISOR=P.RFCEMISOR AND F.SERIE=P.SERIE AND F.FOLIO=P.FOLIO INNER JOIN CONDICIONESDEPAGO CP ON F.CONDICIONESDEPAGO=CP.CLAVE INNER JOIN TIPOSCOMPROBANTES T ON F.TIPOCOMPROBANTE=T.CLAVE where F.RFCEMISOR='" + RFCEMISOR + "' AND F.SERIE='" + SERIE + "' AND F.FOLIO=" + FOLIO.ToString

                        QUERY = "SELECT F.RFCEMISOR,E.NOMBRE NOMBREFISCAL,F.FECHA,F.SERIE,F.SUBTOTAL,F.IVA,F.DESCUENTO,F.TOTAL,F.CCLETRA CANTIDADCONLETRA,F.CERTIFICADOUSA NOCERTIFICADO,F.FOLIO,DBO.DOMICILIOMATRIZ(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOMATRIZ,DBO.DOMICILIOEXPEDICION(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOEXPEDICION,E.LOGOTIPO,E.LOGORFC,F.RFCCLIENTE,F.NOMBRE NOMBRECLIENTE,DBO.DIRECCIONCLI1(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI1,DBO.DIRECCIONCLI2(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI2,M.NOMBRE METODOPAGO,FP.NOMBRE FORMAPAGO,F.CADENAORIGINAL,F.SELLO SELLODIGITAL,F.SELLOSAT,F.UUID,P.CODIGO,P.CANTIDAD,P.UNIDAD, P.DESCRIPCION,P.VALORUNITARIO,P.IMPORTE,F.DIGITOSTC,E.REGIMEN,TXTPAGARE=DBO.TXTPAGARE(F.RFCEMISOR,F.SERIE,F.FOLIO),F.CBB CBBFACTURA,P.IEPS,F.COMENTARIO,P.IVA DIVA,IMPORTELIC=(P.IMPORTE+P.IVA+P.IEPS-P.DESCUENTO),F.RETISR,F.RETIVA,E.CURP,F.COCSAT,P.DESCUENTO DESCUENTOD,CP.NOMBRE CONDICIONESDEPAGO,T.DESCRIPCION TIPOCOMPROBANTE,MD.NOMBRE MOTIVO FROM FACTURAS F INNER JOIN EMISORES E ON F.RFCEMISOR=E.RFC INNER JOIN FORMASPAGO FP ON F.FORMAPAGO=FP.CLAVE INNER JOIN METODOSPAGOS M ON F.METODOPAGO=M.CLAVE INNER JOIN CONFIGURACION CON ON E.RFC=CON.RFC INNER JOIN NEGOCIOS N ON F.RFCEMISOR=N.RFC AND F.NEGOCIO=N.CLAVE INNER JOIN CLIENTES C ON F.RFCCLIENTE=C.RFC INNER JOIN DOMICILIOSCLIENTES D ON F.RFCCLIENTE=D.RFC AND F.DOMICILIOCLIENTE=D.REGISTRO INNER JOIN DETALLEFACTURAS P ON F.RFCEMISOR=P.RFCEMISOR AND F.SERIE=P.SERIE AND F.FOLIO=P.FOLIO INNER JOIN CONDICIONESDEPAGO CP ON F.CONDICIONESDEPAGO=CP.CLAVE INNER JOIN TIPOSCOMPROBANTES T ON F.TIPOCOMPROBANTE=T.CLAVE INNER JOIN MOTIVODOCTO MD ON F.TIPO=MD.CLAVE where F.RFCEMISOR='" + CBEMISOR.Text + "' AND F.SERIE='" + DGV.Item(1, X).Value.ToString + "' AND F.FOLIO=" + DGV.Item(2, X).Value.ToString
                        QUERY = "SELECT * FROM VRFACTURA F where F.RFCEMISOR='" + CBEMISOR.Text + "' AND F.SERIE='" + DGV.Item(1, X).Value.ToString + "' AND F.FOLIO=" + DGV.Item(2, X).Value.ToString
                        If CType(DGV.Item(10, X).Value, Double) > 0 Or CType(DGV.Item(11, DGV.CurrentRow.Index).Value, Double) > 0 Or CBEMISOR.Text = "COVM930214167" Or CBEMISOR.Text = "VEAA6508272F2" Then
                            If DGV.Item(14, X).Value = "3.2" Then
                                Dim REP As New rptFEBAJAMARISR
                                IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                            ElseIf DGV.Item(14, X).Value = "2.0" Then
                                Dim REP As New rptFEBAJAMARISR
                                IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                            Else
                                Dim REP As New rptFEBAJAMARISR
                                IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                            End If
                        Else
                            If DGV.Item(14, X).Value = "3.2" Then
                                If ESTADO = "Cancelada" Then
                                    Dim REP As New rptFEBAJAMARCANC
                                    IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                                Else
                                    Dim REP As New rptFEBAJAMAR3
                                    IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                                End If
                            ElseIf DGV.Item(14, X).Value = "2.0" Then
                                If ESTADO = "Cancelada" Then
                                    Dim REP As New rptFEBAJAMARCANC
                                    IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                                Else
                                    Dim REP As New rptFEBAJAMAR3
                                    IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                                End If
                            Else
                                If ESTADO = "Cancelada" Then
                                    Dim REP As New rptFEBAJAMARCANC
                                    IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                                Else
                                    Dim REP As New rptFEBAJAMAR3
                                    IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                                End If
                            End If
                        End If

                    Else
                        'QUERY = "SELECT F.RFCEMISOR,E.NOMBRE NOMBREFISCAL,F.FECHA,F.SERIE,F.SUBTOTAL,F.IVA,F.DESCUENTO,F.TOTAL,F.CCLETRA CANTIDADCONLETRA,CON.NOCERTIFICADO,F.FOLIO,DBO.DOMICILIOMATRIZ(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOMATRIZ,DBO.DOMICILIOEXPEDICION(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOEXPEDICION,E.LOGOTIPO,E.LOGORFC,F.RFCCLIENTE,F.NOMBRE NOMBRECLIENTE,DBO.DIRECCIONCLI1(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI1,DBO.DIRECCIONCLI2(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI2,M.NOMBRE METODOPAGO,FP.NOMBRE FORMAPAGO,F.CADENAORIGINAL,F.SELLO SELLODIGITAL,F.SELLOSAT, F.UUID, P.CODIGO, P.CANTIDAD, P.DESCRIPCION, P.VALORUNITARIO,P.IMPORTE FROM FACTURAS F INNER JOIN EMISORES E ON F.RFCEMISOR=E.RFC INNER JOIN FORMASPAGO FP ON F.FORMAPAGO=FP.CLAVE INNER JOIN METODOSPAGOS M ON F.METODOPAGO=M.CLAVE INNER JOIN CONFIGURACION CON ON E.RFC=CON.RFC INNER JOIN NEGOCIOS N ON F.RFCEMISOR=N.RFC AND F.NEGOCIO=N.CLAVE INNER JOIN CLIENTES C ON F.RFCCLIENTE=C.RFC INNER JOIN DOMICILIOSCLIENTES D ON F.RFCCLIENTE=D.RFC AND F.DOMICILIOCLIENTE=D.REGISTRO INNER JOIN DETALLEFACTURAS P ON F.RFCEMISOR=P.RFCEMISOR AND F.SERIE=P.SERIE AND F.FOLIO=P.FOLIO where F.RFCEMISOR='" + CBEMISOR.Text + "' AND F.SERIE='" + DGV.Item(1, DGV.CurrentRow.Index).Value.ToString + "' AND F.FOLIO=" + DGV.Item(2, DGV.CurrentRow.Index).Value.ToString
                        'Dim REP As New rptFacturaElectronica3
                        'MOSTRARREPORTE(REP, "Reporte de Factura", LLENATABLA(QUERY, frmPrincipal.CadenaConexion), "")
                        'QUERY = "SELECT F.RFCEMISOR,E.NOMBRE NOMBREFISCAL,F.FECHA,F.SERIE,F.SUBTOTAL,F.IVA,F.DESCUENTO,F.TOTAL,F.CCLETRA CANTIDADCONLETRA,F.CERTIFICADOUSA NOCERTIFICADO,F.FOLIO,DBO.DOMICILIOMATRIZ(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOMATRIZ,DBO.DOMICILIOEXPEDICION(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOEXPEDICION,E.LOGOTIPO,E.LOGORFC,E.LOGOBIDIMENSIONAL CBBEMISOR,F.RFCCLIENTE,F.NOMBRE NOMBRECLIENTE,DBO.DIRECCIONCLI1(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI1,DBO.DIRECCIONCLI2(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI2,M.NOMBRE METODOPAGO,FP.NOMBRE FORMAPAGO,F.CADENAORIGINAL,F.SELLO SELLODIGITAL,F.SELLOSAT,F.UUID,P.CODIGO,P.CANTIDAD,P.DESCRIPCION,CONVERT(NUMERIC(15,2),P.VALORUNITARIO,2)VALORUNITARIO,CONVERT(NUMERIC(15,2),P.IMPORTE,2)IMPORTE,F.RETISR,F.RETIVA,F.NOAPROBACION,F.AÑOAPROBACION,F.CBB CBBFACTURA,P.UNIDAD,F.DIGITOSTC,E.REGIMEN,TXTPAGARE=DBO.TXTPAGARE(F.RFCEMISOR,F.SERIE,F.FOLIO),F.COMENTARIO,P.IEPS,P.IVA DIVA,IMPORTELIC=(P.IMPORTE+P.IVA+P.IEPS),E.CURP,F.COCSAT,P.DESCUENTO DESCUENTOD,CP.NOMBRE CONDICIONESDEPAGO,T.DESCRIPCION TIPOCOMPROBANTE FROM FACTURAS F INNER JOIN EMISORES E ON F.RFCEMISOR=E.RFC INNER JOIN FORMASPAGO FP ON F.FORMAPAGO=FP.CLAVE INNER JOIN METODOSPAGOS M ON F.METODOPAGO=M.CLAVE INNER JOIN CONFIGURACION CON ON E.RFC=CON.RFC INNER JOIN NEGOCIOS N ON F.RFCEMISOR=N.RFC AND F.NEGOCIO=N.CLAVE INNER JOIN CLIENTES C ON F.RFCCLIENTE=C.RFC INNER JOIN DOMICILIOSCLIENTES D ON F.RFCCLIENTE=D.RFC AND F.DOMICILIOCLIENTE=D.REGISTRO INNER JOIN DETALLEFACTURAS P ON F.RFCEMISOR=P.RFCEMISOR AND F.SERIE=P.SERIE AND F.FOLIO=P.FOLIO INNER JOIN CONDICIONESDEPAGO CP ON F.CONDICIONESDEPAGO=CP.CLAVE INNER JOIN TIPOSCOMPROBANTES T ON F.TIPOCOMPROBANTE=T.CLAVE where F.RFCEMISOR='" + RFCEMISOR + "' AND F.SERIE='" + SERIE + "' AND F.FOLIO=" + FOLIO.ToString

                        QUERY = "SELECT F.RFCEMISOR,E.NOMBRE NOMBREFISCAL,F.FECHA,F.SERIE,F.SUBTOTAL,F.IVA,F.DESCUENTO,F.TOTAL,F.CCLETRA CANTIDADCONLETRA,F.CERTIFICADOUSA NOCERTIFICADO,F.FOLIO,DBO.DOMICILIOMATRIZ(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOMATRIZ,DBO.DOMICILIOEXPEDICION(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOEXPEDICION,E.LOGOTIPO,E.LOGORFC,F.RFCCLIENTE,F.NOMBRE NOMBRECLIENTE,DBO.DIRECCIONCLI1(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI1,DBO.DIRECCIONCLI2(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI2,M.NOMBRE METODOPAGO,FP.NOMBRE FORMAPAGO,F.CADENAORIGINAL,F.SELLO SELLODIGITAL,F.SELLOSAT,F.UUID,P.CODIGO,P.CANTIDAD,P.UNIDAD, P.DESCRIPCION,P.VALORUNITARIO,P.IMPORTE,F.DIGITOSTC,E.REGIMEN,TXTPAGARE=DBO.TXTPAGARE(F.RFCEMISOR,F.SERIE,F.FOLIO),F.CBB CBBFACTURA,P.IEPS,F.COMENTARIO,P.IVA DIVA,IMPORTELIC=(P.IMPORTE+P.IVA+P.IEPS-P.DESCUENTO),F.RETISR,F.RETIVA,E.CURP,F.COCSAT,P.DESCUENTO DESCUENTOD,CP.NOMBRE CONDICIONESDEPAGO,T.DESCRIPCION TIPOCOMPROBANTE,MD.NOMBRE MOTIVO FROM FACTURAS F INNER JOIN EMISORES E ON F.RFCEMISOR=E.RFC INNER JOIN FORMASPAGO FP ON F.FORMAPAGO=FP.CLAVE INNER JOIN METODOSPAGOS M ON F.METODOPAGO=M.CLAVE INNER JOIN CONFIGURACION CON ON E.RFC=CON.RFC INNER JOIN NEGOCIOS N ON F.RFCEMISOR=N.RFC AND F.NEGOCIO=N.CLAVE INNER JOIN CLIENTES C ON F.RFCCLIENTE=C.RFC INNER JOIN DOMICILIOSCLIENTES D ON F.RFCCLIENTE=D.RFC AND F.DOMICILIOCLIENTE=D.REGISTRO INNER JOIN DETALLEFACTURAS P ON F.RFCEMISOR=P.RFCEMISOR AND F.SERIE=P.SERIE AND F.FOLIO=P.FOLIO INNER JOIN CONDICIONESDEPAGO CP ON F.CONDICIONESDEPAGO=CP.CLAVE INNER JOIN TIPOSCOMPROBANTES T ON F.TIPOCOMPROBANTE=T.CLAVE INNER JOIN MOTIVODOCTO MD ON F.TIPO=MD.CLAVE where F.RFCEMISOR='" + CBEMISOR.Text + "' AND F.SERIE='" + DGV.Item(1, X).Value.ToString + "' AND F.FOLIO=" + DGV.Item(2, X).Value.ToString
                        QUERY = "SELECT * FROM VRFACTURA F where F.RFCEMISOR='" + CBEMISOR.Text + "' AND F.SERIE='" + DGV.Item(1, X).Value.ToString + "' AND F.FOLIO=" + DGV.Item(2, X).Value.ToString
                        'QUERY = "SELECT F.RFCEMISOR,E.NOMBRE NOMBREFISCAL,F.FECHA,F.SERIE,F.SUBTOTAL,F.IVA,F.DESCUENTO,F.TOTAL,F.CCLETRA CANTIDADCONLETRA,CON.NOCERTIFICADO,F.FOLIO,DBO.DOMICILIOMATRIZ(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOMATRIZ,DBO.DOMICILIOEXPEDICION(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOEXPEDICION,E.LOGOTIPO,E.LOGORFC,F.RFCCLIENTE,F.NOMBRE NOMBRECLIENTE,DBO.DIRECCIONCLI1(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI1,DBO.DIRECCIONCLI2(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI2,M.NOMBRE METODOPAGO,FP.NOMBRE FORMAPAGO,F.CADENAORIGINAL,F.SELLO SELLODIGITAL,F.SELLOSAT, F.UUID, P.CODIGO, P.CANTIDAD,P.UNIDAD, P.DESCRIPCION, P.VALORUNITARIO,P.IMPORTE,F.DIGITOSTC,E.REGIMEN,F.CBB CBBFACTURA FROM FACTURAS F INNER JOIN EMISORES E ON F.RFCEMISOR=E.RFC INNER JOIN FORMASPAGO FP ON F.FORMAPAGO=FP.CLAVE INNER JOIN METODOSPAGOS M ON F.METODOPAGO=M.CLAVE INNER JOIN CONFIGURACION CON ON E.RFC=CON.RFC INNER JOIN NEGOCIOS N ON F.RFCEMISOR=N.RFC AND F.NEGOCIO=N.CLAVE INNER JOIN CLIENTES C ON F.RFCCLIENTE=C.RFC INNER JOIN DOMICILIOSCLIENTES D ON F.RFCCLIENTE=D.RFC AND F.DOMICILIOCLIENTE=D.REGISTRO INNER JOIN DETALLEFACTURAS P ON F.RFCEMISOR=P.RFCEMISOR AND F.SERIE=P.SERIE AND F.FOLIO=P.FOLIO where F.RFCEMISOR='" + CBEMISOR.Text + "' AND F.SERIE='" + DGV.Item(1, X).Value.ToString + "' AND F.FOLIO=" + DGV.Item(2, X).Value.ToString
                        If CType(DGV.Item(10, X).Value, Double) > 0 Or CType(DGV.Item(11, X).Value, Double) > 0 Or CBEMISOR.Text = "COVM930214167" Or CBEMISOR.Text = "VEAA6508272F2" Then
                            If DGV.Item(14, X).Value = "3.0" Then
                                Dim REP As New rptFEBAJAMARISR
                                IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                            Else
                                Dim REP As New rptFEBAJAMARISR
                                IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                            End If
                        Else
                            If DGV.Item(14, X).Value = "3.0" Then
                                If ESTADO = "Cancelada" Then
                                    Dim REP As New rptFEBAJAMARCANC
                                    IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                                Else
                                    Dim REP As New rptFEBAJAMAR3
                                    IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                                End If
                            Else
                                If ESTADO = "Cancelada" Then
                                    Dim REP As New rptFEBAJAMARCANC
                                    IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                                Else
                                    Dim REP As New rptFEBAJAMAR3
                                    IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, NI)
                                End If
                            End If
                        End If
                    End If
                End If
               
                'If LTIPO(CBEMISOR.SelectedIndex) = 2 Then
                '    QUERY = "SELECT F.RFCEMISOR,E.NOMBRE NOMBREFISCAL,F.FECHA,F.SERIE,F.SUBTOTAL,F.IVA,F.DESCUENTO,F.TOTAL,F.CCLETRA CANTIDADCONLETRA,NOCERTIFICADO='00001000000104182352',F.FOLIO,DBO.DOMICILIOMATRIZ(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOMATRIZ,DBO.DOMICILIOEXPEDICION(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOEXPEDICION,E.LOGOTIPO,E.LOGORFC,E.LOGOBIDIMENSIONAL CBBEMISOR,F.RFCCLIENTE,F.NOMBRE NOMBRECLIENTE,DBO.DIRECCIONCLI1(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI1,DBO.DIRECCIONCLI2(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI2,M.NOMBRE METODOPAGO,FP.NOMBRE FORMAPAGO,F.CADENAORIGINAL,F.SELLO SELLODIGITAL,F.SELLOSAT,F.UUID,P.CODIGO,P.CANTIDAD,P.DESCRIPCION,CONVERT(NUMERIC(15,2),P.VALORUNITARIO,2)VALORUNITARIO,CONVERT(NUMERIC(15,2),P.IMPORTE,2)IMPORTE,F.RETISR,F.RETIVA,F.NOAPROBACION,F.AÑOAPROBACION,F.CBB CBBFACTURA,P.UNIDAD,F.DIGITOSTC,E.REGIMEN FROM FACTURAS F INNER JOIN EMISORES E ON F.RFCEMISOR=E.RFC INNER JOIN FORMASPAGO FP ON F.FORMAPAGO=FP.CLAVE INNER JOIN METODOSPAGOS M ON F.METODOPAGO=M.CLAVE INNER JOIN CONFIGURACION CON ON E.RFC=CON.RFC INNER JOIN NEGOCIOS N ON F.RFCEMISOR=N.RFC AND F.NEGOCIO=N.CLAVE INNER JOIN CLIENTES C ON F.RFCCLIENTE=C.RFC INNER JOIN DOMICILIOSCLIENTES D ON F.RFCCLIENTE=D.RFC AND F.DOMICILIOCLIENTE=D.REGISTRO INNER JOIN DETALLEFACTURAS P ON F.RFCEMISOR=P.RFCEMISOR AND F.SERIE=P.SERIE AND F.FOLIO=P.FOLIO  where F.RFCEMISOR='" + CBEMISOR.Text + "' AND F.SERIE='" + DGV.Item(1, X).Value.ToString + "' AND F.FOLIO=" + DGV.Item(2, X).Value.ToString
                '    If DGV.Item(14, X).Value = "2.0" Then
                '        Dim REP As New rptFacturaElectronica4
                '        IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, "")
                '    Else
                '        Dim REP As New rptFacturaElectronicaV2_2
                '        IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, "")
                '    End If

                'Else
                '    QUERY = "SELECT F.RFCEMISOR,E.NOMBRE NOMBREFISCAL,F.FECHA,F.SERIE,F.SUBTOTAL,F.IVA,F.DESCUENTO,F.TOTAL,F.CCLETRA CANTIDADCONLETRA,CON.NOCERTIFICADO,F.FOLIO,DBO.DOMICILIOMATRIZ(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOMATRIZ,DBO.DOMICILIOEXPEDICION(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICILIOEXPEDICION,E.LOGOTIPO,E.LOGORFC,F.RFCCLIENTE,F.NOMBRE NOMBRECLIENTE,DBO.DIRECCIONCLI1(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI1,DBO.DIRECCIONCLI2(F.RFCEMISOR,F.SERIE,F.FOLIO)DOMICLIOCLI2,M.NOMBRE METODOPAGO,FP.NOMBRE FORMAPAGO,F.CADENAORIGINAL,F.SELLO SELLODIGITAL,F.SELLOSAT, F.UUID, P.CODIGO, P.CANTIDAD,P.UNIDAD, P.DESCRIPCION, P.VALORUNITARIO,P.IMPORTE,F.DIGITOSTC,E.REGIMEN,F.CBB CBBFACTURA FROM FACTURAS F INNER JOIN EMISORES E ON F.RFCEMISOR=E.RFC INNER JOIN FORMASPAGO FP ON F.FORMAPAGO=FP.CLAVE INNER JOIN METODOSPAGOS M ON F.METODOPAGO=M.CLAVE INNER JOIN CONFIGURACION CON ON E.RFC=CON.RFC INNER JOIN NEGOCIOS N ON F.RFCEMISOR=N.RFC AND F.NEGOCIO=N.CLAVE INNER JOIN CLIENTES C ON F.RFCCLIENTE=C.RFC INNER JOIN DOMICILIOSCLIENTES D ON F.RFCCLIENTE=D.RFC AND F.DOMICILIOCLIENTE=D.REGISTRO INNER JOIN DETALLEFACTURAS P ON F.RFCEMISOR=P.RFCEMISOR AND F.SERIE=P.SERIE AND F.FOLIO=P.FOLIO where F.RFCEMISOR='" + CBEMISOR.Text + "' AND F.SERIE='" + DGV.Item(1, X).Value.ToString + "' AND F.FOLIO=" + DGV.Item(2, X).Value.ToString
                '    If CType(DGV.Item(10, X).Value, Double) > 0 Then
                '        If DGV.Item(14, X).Value = "3.0" Then
                '            Dim REP As New rptFacturaElectronica2
                '            IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, "")
                '        Else
                '            Dim REP As New rptFEBAJAMAR
                '            IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, "")
                '        End If
                '    Else
                '        If DGV.Item(14, X).Value = "3.0" Then
                '            Dim REP As New rptFacturaElectronica3
                '            IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, "")
                '        Else
                '            Dim REP As New rptFEBAJAMAR
                '            IMPRIMIRREPORTE(REP, LLENATABLA(QUERY, frmPrincipal.CadenaConexion), 1, "")
                '        End If
                '    End If
                'End If

            End If
        Next
    End Sub

    Private Sub SIIMP_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles SIIMP.Click
        Dim XYZ As Short
        XYZ = MessageBox.Show("Desea Marcar los Datos", "Aviso", MessageBoxButtons.YesNo, MessageBoxIcon.Question, MessageBoxDefaultButton.Button1)
        If XYZ = 6 Then
            Dim X As Integer
            For X = 0 To DGV.Rows.Count - 1
                DGV.Item(12, X).Value = True
            Next
            CHECATABLA()
        End If
    End Sub

    Private Sub NOIMP_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles NOIMP.Click
        Dim XYZ As Short
        XYZ = MessageBox.Show("Desea Desmarcar los Datos", "Aviso", MessageBoxButtons.YesNo, MessageBoxIcon.Question, MessageBoxDefaultButton.Button1)
        If XYZ = 6 Then
            Dim X As Integer
            For X = 0 To DGV.Rows.Count - 1
                DGV.Item(12, X).Value = False
            Next
            CHECATABLA()
        End If
    End Sub
End Class