'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WSCLIENTE
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Application", [Namespace]:="http://facturacion.finkok.com/registration")>  _
    Partial Public Class RegistrationSOAP
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private customersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getOperationCompleted As System.Threading.SendOrPostCallback
        
        Private editOperationCompleted As System.Threading.SendOrPostCallback
        
        Private switchOperationCompleted As System.Threading.SendOrPostCallback
        
        Private addOperationCompleted As System.Threading.SendOrPostCallback
        
        Private assignOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.FacturacionGZ.My.MySettings.Default.FacturacionGZ_WSCLIENTE_RegistrationSOAP
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event customersCompleted As customersCompletedEventHandler
        
        '''<remarks/>
        Public Event getCompleted As getCompletedEventHandler
        
        '''<remarks/>
        Public Event editCompleted As editCompletedEventHandler
        
        '''<remarks/>
        Public Event switchCompleted As switchCompletedEventHandler
        
        '''<remarks/>
        Public Event addCompleted As addCompletedEventHandler
        
        '''<remarks/>
        Public Event assignCompleted As assignCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("customers", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function customers(<System.Xml.Serialization.XmlElementAttribute("customers", [Namespace]:="http://facturacion.finkok.com/registration")> ByVal customers1 As customers) As <System.Xml.Serialization.XmlElementAttribute("customersResponse", [Namespace]:="http://facturacion.finkok.com/registration")> customersResponse
            Dim results() As Object = Me.Invoke("customers", New Object() {customers1})
            Return CType(results(0),customersResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub customersAsync(ByVal customers1 As customers)
            Me.customersAsync(customers1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub customersAsync(ByVal customers1 As customers, ByVal userState As Object)
            If (Me.customersOperationCompleted Is Nothing) Then
                Me.customersOperationCompleted = AddressOf Me.OncustomersOperationCompleted
            End If
            Me.InvokeAsync("customers", New Object() {customers1}, Me.customersOperationCompleted, userState)
        End Sub
        
        Private Sub OncustomersOperationCompleted(ByVal arg As Object)
            If (Not (Me.customersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent customersCompleted(Me, New customersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("get", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function [get](<System.Xml.Serialization.XmlElementAttribute("get", [Namespace]:="http://facturacion.finkok.com/registration")> ByVal get1 As [get]) As <System.Xml.Serialization.XmlElementAttribute("getResponse", [Namespace]:="http://facturacion.finkok.com/registration")> getResponse
            Dim results() As Object = Me.Invoke("get", New Object() {get1})
            Return CType(results(0),getResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getAsync(ByVal get1 As [get])
            Me.getAsync(get1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getAsync(ByVal get1 As [get], ByVal userState As Object)
            If (Me.getOperationCompleted Is Nothing) Then
                Me.getOperationCompleted = AddressOf Me.OngetOperationCompleted
            End If
            Me.InvokeAsync("get", New Object() {get1}, Me.getOperationCompleted, userState)
        End Sub
        
        Private Sub OngetOperationCompleted(ByVal arg As Object)
            If (Not (Me.getCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getCompleted(Me, New getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("edit", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function edit(<System.Xml.Serialization.XmlElementAttribute("edit", [Namespace]:="http://facturacion.finkok.com/registration")> ByVal edit1 As edit) As <System.Xml.Serialization.XmlElementAttribute("editResponse", [Namespace]:="http://facturacion.finkok.com/registration")> editResponse
            Dim results() As Object = Me.Invoke("edit", New Object() {edit1})
            Return CType(results(0),editResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub editAsync(ByVal edit1 As edit)
            Me.editAsync(edit1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub editAsync(ByVal edit1 As edit, ByVal userState As Object)
            If (Me.editOperationCompleted Is Nothing) Then
                Me.editOperationCompleted = AddressOf Me.OneditOperationCompleted
            End If
            Me.InvokeAsync("edit", New Object() {edit1}, Me.editOperationCompleted, userState)
        End Sub
        
        Private Sub OneditOperationCompleted(ByVal arg As Object)
            If (Not (Me.editCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent editCompleted(Me, New editCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("switch", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function switch(<System.Xml.Serialization.XmlElementAttribute("switch", [Namespace]:="http://facturacion.finkok.com/registration")> ByVal switch1 As switch) As <System.Xml.Serialization.XmlElementAttribute("switchResponse", [Namespace]:="http://facturacion.finkok.com/registration")> switchResponse
            Dim results() As Object = Me.Invoke("switch", New Object() {switch1})
            Return CType(results(0),switchResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub switchAsync(ByVal switch1 As switch)
            Me.switchAsync(switch1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub switchAsync(ByVal switch1 As switch, ByVal userState As Object)
            If (Me.switchOperationCompleted Is Nothing) Then
                Me.switchOperationCompleted = AddressOf Me.OnswitchOperationCompleted
            End If
            Me.InvokeAsync("switch", New Object() {switch1}, Me.switchOperationCompleted, userState)
        End Sub
        
        Private Sub OnswitchOperationCompleted(ByVal arg As Object)
            If (Not (Me.switchCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent switchCompleted(Me, New switchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("add", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function add(<System.Xml.Serialization.XmlElementAttribute("add", [Namespace]:="http://facturacion.finkok.com/registration")> ByVal add1 As add) As <System.Xml.Serialization.XmlElementAttribute("addResponse", [Namespace]:="http://facturacion.finkok.com/registration")> addResponse
            Dim results() As Object = Me.Invoke("add", New Object() {add1})
            Return CType(results(0),addResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub addAsync(ByVal add1 As add)
            Me.addAsync(add1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub addAsync(ByVal add1 As add, ByVal userState As Object)
            If (Me.addOperationCompleted Is Nothing) Then
                Me.addOperationCompleted = AddressOf Me.OnaddOperationCompleted
            End If
            Me.InvokeAsync("add", New Object() {add1}, Me.addOperationCompleted, userState)
        End Sub
        
        Private Sub OnaddOperationCompleted(ByVal arg As Object)
            If (Not (Me.addCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent addCompleted(Me, New addCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("assign", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function assign(<System.Xml.Serialization.XmlElementAttribute("assign", [Namespace]:="http://facturacion.finkok.com/registration")> ByVal assign1 As assign) As <System.Xml.Serialization.XmlElementAttribute("assignResponse", [Namespace]:="http://facturacion.finkok.com/registration")> assignResponse
            Dim results() As Object = Me.Invoke("assign", New Object() {assign1})
            Return CType(results(0),assignResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub assignAsync(ByVal assign1 As assign)
            Me.assignAsync(assign1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub assignAsync(ByVal assign1 As assign, ByVal userState As Object)
            If (Me.assignOperationCompleted Is Nothing) Then
                Me.assignOperationCompleted = AddressOf Me.OnassignOperationCompleted
            End If
            Me.InvokeAsync("assign", New Object() {assign1}, Me.assignOperationCompleted, userState)
        End Sub
        
        Private Sub OnassignOperationCompleted(ByVal arg As Object)
            If (Not (Me.assignCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent assignCompleted(Me, New assignCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/registration")>  _
    Partial Public Class customers
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private pageField As String
        
        '''<remarks/>
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property page() As String
            Get
                Return Me.pageField
            End Get
            Set
                Me.pageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class AssingResult
        
        Private successField As System.Nullable(Of Boolean)
        
        Private successFieldSpecified As Boolean
        
        Private creditField As String
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property success() As System.Nullable(Of Boolean)
            Get
                Return Me.successField
            End Get
            Set
                Me.successField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property successSpecified() As Boolean
            Get
                Return Me.successFieldSpecified
            End Get
            Set
                Me.successFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", IsNullable:=true)>  _
        Public Property credit() As String
            Get
                Return Me.creditField
            End Get
            Set
                Me.creditField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/registration")>  _
    Partial Public Class assignResponse
        
        Private assignResultField As AssingResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property assignResult() As AssingResult
            Get
                Return Me.assignResultField
            End Get
            Set
                Me.assignResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/registration")>  _
    Partial Public Class assign
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private taxpayer_idField As String
        
        Private creditField As String
        
        '''<remarks/>
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property taxpayer_id() As String
            Get
                Return Me.taxpayer_idField
            End Get
            Set
                Me.taxpayer_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger", IsNullable:=true)>  _
        Public Property credit() As String
            Get
                Return Me.creditField
            End Get
            Set
                Me.creditField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/registration")>  _
    Partial Public Class addResponse
        
        Private addResultField As RegistrationResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property addResult() As RegistrationResult
            Get
                Return Me.addResultField
            End Get
            Set
                Me.addResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class RegistrationResult
        
        Private messageField As String
        
        Private successField As System.Nullable(Of Boolean)
        
        Private successFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property success() As System.Nullable(Of Boolean)
            Get
                Return Me.successField
            End Get
            Set
                Me.successField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property successSpecified() As Boolean
            Get
                Return Me.successFieldSpecified
            End Get
            Set
                Me.successFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/registration")>  _
    Partial Public Class add
        
        Private reseller_usernameField As String
        
        Private reseller_passwordField As String
        
        Private taxpayer_idField As String
        
        Private type_userField As String
        
        Private couponField As String
        
        Private addedField As String
        
        Private cerField() As Byte
        
        Private keyField() As Byte
        
        Private passphraseField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property reseller_username() As String
            Get
                Return Me.reseller_usernameField
            End Get
            Set
                Me.reseller_usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property reseller_password() As String
            Get
                Return Me.reseller_passwordField
            End Get
            Set
                Me.reseller_passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property taxpayer_id() As String
            Get
                Return Me.taxpayer_idField
            End Get
            Set
                Me.taxpayer_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property type_user() As String
            Get
                Return Me.type_userField
            End Get
            Set
                Me.type_userField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property coupon() As String
            Get
                Return Me.couponField
            End Get
            Set
                Me.couponField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property added() As String
            Get
                Return Me.addedField
            End Get
            Set
                Me.addedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
        Public Property cer() As Byte()
            Get
                Return Me.cerField
            End Get
            Set
                Me.cerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
        Public Property key() As Byte()
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property passphrase() As String
            Get
                Return Me.passphraseField
            End Get
            Set
                Me.passphraseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class SwitchResult
        
        Private messageField As String
        
        Private successField As System.Nullable(Of Boolean)
        
        Private successFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property success() As System.Nullable(Of Boolean)
            Get
                Return Me.successField
            End Get
            Set
                Me.successField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property successSpecified() As Boolean
            Get
                Return Me.successFieldSpecified
            End Get
            Set
                Me.successFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/registration")>  _
    Partial Public Class switchResponse
        
        Private switchResultField As SwitchResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property switchResult() As SwitchResult
            Get
                Return Me.switchResultField
            End Get
            Set
                Me.switchResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/registration")>  _
    Partial Public Class switch
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private taxpayer_idField As String
        
        Private type_userField As String
        
        '''<remarks/>
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property taxpayer_id() As String
            Get
                Return Me.taxpayer_idField
            End Get
            Set
                Me.taxpayer_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property type_user() As String
            Get
                Return Me.type_userField
            End Get
            Set
                Me.type_userField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/registration")>  _
    Partial Public Class editResponse
        
        Private editResultField As RegistrationResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property editResult() As RegistrationResult
            Get
                Return Me.editResultField
            End Get
            Set
                Me.editResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/registration")>  _
    Partial Public Class edit
        
        Private reseller_usernameField As String
        
        Private reseller_passwordField As String
        
        Private taxpayer_idField As String
        
        Private statusField As String
        
        Private cerField() As Byte
        
        Private keyField() As Byte
        
        Private passphraseField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property reseller_username() As String
            Get
                Return Me.reseller_usernameField
            End Get
            Set
                Me.reseller_usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property reseller_password() As String
            Get
                Return Me.reseller_passwordField
            End Get
            Set
                Me.reseller_passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property taxpayer_id() As String
            Get
                Return Me.taxpayer_idField
            End Get
            Set
                Me.taxpayer_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
        Public Property cer() As Byte()
            Get
                Return Me.cerField
            End Get
            Set
                Me.cerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
        Public Property key() As Byte()
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property passphrase() As String
            Get
                Return Me.passphraseField
            End Get
            Set
                Me.passphraseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class RegistrationListResult
        
        Private messageField As String
        
        Private usersField() As ResellerUser
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property users() As ResellerUser()
            Get
                Return Me.usersField
            End Get
            Set
                Me.usersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class ResellerUser
        
        Private statusField As String
        
        Private counterField As String
        
        Private taxpayer_idField As String
        
        Private creditField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", IsNullable:=true)>  _
        Public Property counter() As String
            Get
                Return Me.counterField
            End Get
            Set
                Me.counterField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property taxpayer_id() As String
            Get
                Return Me.taxpayer_idField
            End Get
            Set
                Me.taxpayer_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", IsNullable:=true)>  _
        Public Property credit() As String
            Get
                Return Me.creditField
            End Get
            Set
                Me.creditField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/registration")>  _
    Partial Public Class getResponse
        
        Private getResultField As RegistrationListResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property getResult() As RegistrationListResult
            Get
                Return Me.getResultField
            End Get
            Set
                Me.getResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/registration")>  _
    Partial Public Class [get]
        
        Private reseller_usernameField As String
        
        Private reseller_passwordField As String
        
        Private taxpayer_idField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property reseller_username() As String
            Get
                Return Me.reseller_usernameField
            End Get
            Set
                Me.reseller_usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property reseller_password() As String
            Get
                Return Me.reseller_passwordField
            End Get
            Set
                Me.reseller_passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property taxpayer_id() As String
            Get
                Return Me.taxpayer_idField
            End Get
            Set
                Me.taxpayer_idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class CustomersResult
        
        Private messageField As String
        
        Private usersField() As ResellerUser
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property users() As ResellerUser()
            Get
                Return Me.usersField
            End Get
            Set
                Me.usersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/registration")>  _
    Partial Public Class customersResponse
        
        Private customersResultField As CustomersResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property customersResult() As CustomersResult
            Get
                Return Me.customersResultField
            End Get
            Set
                Me.customersResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub customersCompletedEventHandler(ByVal sender As Object, ByVal e As customersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class customersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As customersResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),customersResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub getCompletedEventHandler(ByVal sender As Object, ByVal e As getCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As getResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),getResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub editCompletedEventHandler(ByVal sender As Object, ByVal e As editCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class editCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As editResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),editResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub switchCompletedEventHandler(ByVal sender As Object, ByVal e As switchCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class switchCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As switchResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),switchResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub addCompletedEventHandler(ByVal sender As Object, ByVal e As addCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class addCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As addResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),addResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub assignCompletedEventHandler(ByVal sender As Object, ByVal e As assignCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class assignCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As assignResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),assignResponse)
            End Get
        End Property
    End Class
End Namespace
